include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 100

linter:
  rules:
    lines_longer_than_80_chars: false
analyzer:
  errors:
    use_if_null_to_convert_nulls_to_bools: ignore
