name: anti_mitm
description: A flutter plugin to detect if the mobile device is connected to a proxy or VPN.
version: 0.0.2
homepage: https://thanhdt.dev
repository: https://github.com/thanhdang198/anti_mitm

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.victorblaess.native_flutter_proxy
        pluginClass: FlutterProxyPlugin
      ios:
        pluginClass: FlutterProxyPlugin
